### ISSUE TITLE
Not enough manu

### ISSUE THREAD

**Issue by dcasella** [Marcormio/manu#1]
# NEED MORE MANU
# NEED MORE MANU
# NEED MORE MANU
# NEED MORE MANU
# NEED MORE MANU
# NEED MORE MANU
# NEED MORE MANU

Thanks.

**Comment by dcasella** [comment]
Hello,
is this issue being worked on?

**Comment by Marcormio** [comment]
Hello,
could you be more specific with your need for more manu?

**Comment by dcasella** [comment]
Commit https://github.com/Marcormio/manu/commit/212b0f31ce146101c6bb88dc54946398a20bf740 seems to have fixed my issue.
Thanks.
